name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make /home/runner/work/M1_Bill-estimator_utility/M1_Bill-estimator_utility/3_Implementation
