#TargetName : Dependencies
#<TAB>commands

Build : MainBill.c BillEstimator.c
	gcc MainBill.c BillEstimator.c -o BillEstimator.out

Run : BillEstimator.out
	./BillEstimator.out

Clean :
	rm -rf *.o *.out *.s *.i